#Requires -RunAsAdministrator

<#
.SYNOPSIS
    Enrolls custom UEFI Secure Boot keys inside the Hyper-V guest VM.

.DESCRIPTION
    RUN THIS INSIDE THE VIRTUAL MACHINE -- not on the host.
    SecureBoot must be DISABLED at the Hyper-V host level before running this.

    When a Gen 2 Hyper-V VM has never been started with a SecureBoot template,
    its virtual UEFI contains no keys. This is called UEFI Setup Mode. In Setup
    Mode the firmware accepts unauthenticated writes to UEFI security variables,
    so Set-SecureBootUEFI can enroll keys without needing a pre-signed .auth file.

    Variables are enrolled in this order:
      1. db   -- Signature database (Microsoft UEFI certs + our KM cert)
                 Must be set first so that Windows Boot Manager is trusted
                 when SecureBoot enforcement is later activated.
      2. KEK  -- Key Exchange Key (our PK cert reused)
                 Must be set before PK to satisfy UEFI key hierarchy.
      3. PK   -- Platform Key (our custom cert)
                 Enrolling the PK exits Setup Mode. All subsequent variable
                 updates must be signed by the PK (or KEK for db/dbx).

    After this script completes:
      - SHUT DOWN the VM (Start -> Shut down, not Restart)
      - On the HOST: Set-VMFirmware -VMName <name> -EnableSecureBoot On
      - Start the VM -- SecureBoot is now active with your custom PK
      - Run 04-Deploy-SiPolicy.ps1 inside the VM

.PARAMETER PKIPath
    Path (inside the VM) to the CKS-PKI folder generated by 02-New-CKS-PKI.ps1.

.EXAMPLE
    .\03-Set-UEFI-Keys.ps1 -PKIPath "C:\CKS-PKI"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path $_ -PathType Container })]
    [string]$PKIPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step { param([string]$Msg) Write-Host "[*] $Msg" -ForegroundColor Cyan  }
function Write-OK   { param([string]$Msg) Write-Host "[+] $Msg" -ForegroundColor Green }
function Write-Note { param([string]$Msg) Write-Host "[!] $Msg" -ForegroundColor Yellow }
function Write-Fail { param([string]$Msg) Write-Host "[-] $Msg" -ForegroundColor Red   }

# ---------------------------------------------------------------------------
# Guard: confirm we are inside a virtual machine
# ---------------------------------------------------------------------------
Write-Step "Checking environment"

$model = (Get-CimInstance -ClassName Win32_ComputerSystem -ErrorAction SilentlyContinue).Model
if ($model -notmatch "Virtual|HVM") {
    Write-Note "This machine does not appear to be a virtual machine (Model: $model)."
    $confirm = Read-Host "Are you sure you want to continue? [y/N]"
    if ($confirm -ne "y") { exit 1 }
}

# ---------------------------------------------------------------------------
# Guard: SecureBoot must be OFF (Setup Mode)
#
# Confirm-SecureBootUEFI returns $true if SecureBoot is on and enforcing.
# On a system with SecureBoot off it throws a PlatformNotSupportedException,
# or returns $false. Either is acceptable here.
# ---------------------------------------------------------------------------
$secureBoot = $false
try {
    $secureBoot = Confirm-SecureBootUEFI -ErrorAction Stop
} catch [System.PlatformNotSupportedException] {
    # SecureBoot is off or the UEFI does not support it -- expected for a fresh VM
    $secureBoot = $false
} catch {
    Write-Note "Confirm-SecureBootUEFI returned: $($_.Exception.Message)"
}

if ($secureBoot -eq $true) {
    Write-Fail "SecureBoot is currently ENABLED. This script must run while SecureBoot is OFF."
    Write-Fail "On the Hyper-V HOST, run: Set-VMFirmware -VMName <name> -EnableSecureBoot Off"
    Write-Fail "Then shut down and restart the VM, and run this script again."
    exit 1
}

Write-OK "SecureBoot is off -- UEFI Setup Mode is active"

# ---------------------------------------------------------------------------
# Guard: Set-SecureBootUEFI must be available
# ---------------------------------------------------------------------------
if (-not (Get-Command Set-SecureBootUEFI -ErrorAction SilentlyContinue)) {
    Write-Fail "Set-SecureBootUEFI is not available on this system."
    Write-Fail "This cmdlet requires a UEFI system. Gen 2 Hyper-V VMs are UEFI by default."
    exit 1
}

Write-OK "Set-SecureBootUEFI is available"

# ---------------------------------------------------------------------------
# Guard: required ESL files must be present
# ---------------------------------------------------------------------------
$required = @("db.esl", "kek.esl", "pk.esl")
foreach ($file in $required) {
    $full = Join-Path $PKIPath $file
    if (-not (Test-Path $full)) {
        Write-Fail "Required file not found: $full"
        Write-Fail "Copy the entire CKS-PKI folder into the VM from the host."
        exit 1
    }
}

Write-OK "All required ESL files present in $PKIPath"
Write-Host ""

# ---------------------------------------------------------------------------
# Enroll UEFI variables
#
# In Setup Mode, Set-SecureBootUEFI with -ContentFilePath writes the ESL data
# directly as an unauthenticated variable update. The UEFI firmware accepts
# this because no PK is present to enforce authentication requirements.
#
# Once PK is enrolled (last step), Setup Mode ends and any future updates
# to PK require a signed request from the holder of the old PK private key,
# and updates to KEK/db require a signed request from the PK holder.
# ---------------------------------------------------------------------------

Write-Step "Enrolling db (Signature Database)"
Write-Host "    Contents: Microsoft UEFI certs (for Windows bootloader) + KM cert (for drivers)"
try {
    Set-SecureBootUEFI -Name "db" -ContentFilePath (Join-Path $PKIPath "db.esl")
    Write-OK "db enrolled"
} catch {
    Write-Fail "Failed to enroll db: $($_.Exception.Message)"
    Write-Note "If the error indicates authentication is required, the VM may already have keys enrolled."
    Write-Note "Boot a UEFI Shell and clear all Secure Boot variables, then retry this script."
    exit 1
}

Write-Step "Enrolling KEK (Key Exchange Key)"
try {
    Set-SecureBootUEFI -Name "KEK" -ContentFilePath (Join-Path $PKIPath "kek.esl")
    Write-OK "KEK enrolled"
} catch {
    Write-Fail "Failed to enroll KEK: $($_.Exception.Message)"
    exit 1
}

Write-Step "Enrolling PK (Platform Key) -- this exits UEFI Setup Mode"
try {
    Set-SecureBootUEFI -Name "PK" -ContentFilePath (Join-Path $PKIPath "pk.esl")
    Write-OK "PK enrolled -- UEFI Setup Mode is now CLOSED"
} catch {
    Write-Fail "Failed to enroll PK: $($_.Exception.Message)"
    exit 1
}

# ---------------------------------------------------------------------------
# Verify enrollment (PK and KEK should now be readable)
# ---------------------------------------------------------------------------
Write-Step "Verifying enrollment"

try {
    $pkVar  = Get-SecureBootUEFI -Name PK  -ErrorAction SilentlyContinue
    $kekVar = Get-SecureBootUEFI -Name KEK -ErrorAction SilentlyContinue
    $dbVar  = Get-SecureBootUEFI -Name db  -ErrorAction SilentlyContinue

    if ($pkVar -and $pkVar.Bytes.Length -gt 0) {
        Write-OK ("PK  enrolled ({0} bytes)" -f $pkVar.Bytes.Length)
    } else {
        Write-Note "PK variable returned empty -- enrollment may have failed silently"
    }

    if ($kekVar -and $kekVar.Bytes.Length -gt 0) {
        Write-OK ("KEK enrolled ({0} bytes)" -f $kekVar.Bytes.Length)
    }

    if ($dbVar -and $dbVar.Bytes.Length -gt 0) {
        Write-OK ("db  enrolled ({0} bytes)" -f $dbVar.Bytes.Length)
    }
} catch {
    Write-Note "Verification query returned: $($_.Exception.Message)"
    Write-Note "This may be expected while SecureBoot is still off. Proceed with the next steps."
}

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
Write-Host ""
Write-OK "UEFI key enrollment complete."
Write-Host ""
Write-Note "CRITICAL -- SHUT DOWN (not restart) this VM now, then on the HOST run:"
Write-Host ""
Write-Host "    Set-VMFirmware -VMName <YourVMName> -EnableSecureBoot On"
Write-Host "    Start-VM -Name <YourVMName>"
Write-Host ""
Write-Host "Windows should boot normally. The db contains Microsoft's UEFI certs so"
Write-Host "bootmgfw.efi remains trusted under your custom PK."
Write-Host ""
Write-Note "If Windows fails to boot (BSOD or Secure Boot violation):"
Write-Host "    - Disable SecureBoot again: Set-VMFirmware -EnableSecureBoot Off"
Write-Host "    - Boot the VM and check db.esl contains the correct Microsoft certs"
Write-Host "    - Re-extract ms_db.esl from the HOST and rebuild db.esl via 02-New-CKS-PKI.ps1"
Write-Host ""
Write-Host "After booting successfully with SecureBoot on, run inside the VM:"
Write-Host "    .\04-Deploy-SiPolicy.ps1 -PKIPath '$PKIPath' -EnableCKSExe <path\EnableCKS.exe>"
